host_ip: "127.0.0.1"
is_master_broker: True
duration_s: 60

remote_subscriber_ips: []
remote_publisher_ips: []
connections: []

is_remote_kill: False
remote_kill_ip: null

logging_spec:
  stream_period_s: ${HERMES_EXP_FLUSH_PERIOD_S}
  is_quiet: True

  stream_hdf5: True
  stream_csv: False
  stream_video: False
  stream_audio: False

video_codec_config_filepath: null
audio_codec_config_filepath: null

producer_specs: []

consumer_specs: []

pipeline_specs:
  - package: "dummy"
    class: "DummyPipeline"
    node_id: "probe"
    settings:
      is_async_generate: true
      data_out_spec:
        sampling_rate_hz: ${HERMES_EXP_RATE}
        payload_num_bytes: ${HERMES_EXP_NUM_BYTES}
        buf_len: ${HERMES_EXP_BUF_LEN}
        bundles_not_to_write:
          - "probe"
          - "probe_metadata"
          - "rtt_metadata"

      data_in_specs:
        - package: "dummy"
          class: "DummyEchoPipeline"
          node_id: "echo"
          topics: ["echo"]
          settings:
            sampling_rate_hz: 1
            payload_num_bytes: 1
            buf_len: 1
            bundles_not_to_write:
              - "echo"
              - "echo_metadata"

  - package: "dummy"
    class: "DummyEchoPipeline"
    node_id: "echo"
    settings:
      data_out_spec:
        sampling_rate_hz: 1
        payload_num_bytes: 1
        buf_len: 1
        bundles_not_to_write:
          - "echo"
          - "echo_metadata"

      data_in_specs:
        - package: "dummy"
          class: "DummyPipeline"
          node_id: "probe"
          topics: ["probe"]
          settings:
            sampling_rate_hz: 1
            payload_num_bytes: 1
            buf_len: 1
            bundles_not_to_write:
              - "rtt"
              - "rtt_metadata"
              - "probe"
              - "probe_metadata"

    logging_spec: {}
